// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxjbCSd7BET08NFBmR9g_9a5Z10MmxjYY',
    appId: '1:1078940617108:web:a1ca4779460ca198dfa781',
    messagingSenderId: '1078940617108',
    projectId: 'nexus-chat-930a2',
    authDomain: 'nexus-chat-930a2.firebaseapp.com',
    storageBucket: 'nexus-chat-930a2.firebasestorage.app',
    measurementId: 'G-Q8Z5KMQWMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHdTYk43Wd61x57vScmmSxU1g3K9IoPqc',
    appId: '1:1078940617108:android:3fc65b69c80be897dfa781',
    messagingSenderId: '1078940617108',
    projectId: 'nexus-chat-930a2',
    storageBucket: 'nexus-chat-930a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8CmKkPxpYoV8PMNW4Orb5BTcoLsvpa4Y',
    appId: '1:1078940617108:ios:d3b15411ff67e1e9dfa781',
    messagingSenderId: '1078940617108',
    projectId: 'nexus-chat-930a2',
    storageBucket: 'nexus-chat-930a2.firebasestorage.app',
    iosBundleId: 'com.example.nexusChats',
  );
}
